# From https://oli.me.uk/2018-03-29-clojure-and-clojurescript-tests-on-travis/
sudo: true
language: java
jobs:
  include:
    - stage: unittest
      script: clojure -Atest
    - stage: ancient
      #      script: clojure -Aoutdated
      script: clojure -Aoutdated
install:
  - curl -O https://download.clojure.org/install/linux-install-1.9.0.358.sh
  - chmod +x linux-install-1.9.0.358.sh
  - sudo ./linux-install-1.9.0.358.sh
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gitlibs
#    - .cpcache
